var=input("enter your name")
print("your name is ",var)
var1 = int(input("enter a number"))
var2 = int(input("enter another number"))
print(var1+var2) 
var3 = float(input("enter a number"))
var4 = float(input("enter another number"))
print(var3+var4) 
var3 = input()
var4 = input()
print(var3+var4)
